/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import Vargas.Util;
import beu.Estudiante;
import bll.Gestion_Estudiante;
import java.io.IOException;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;

/**
 *
 * @author labctr
 */
public class frmRegistroEstudiante extends javax.swing.JInternalFrame {

    private final String titulo = "Registrar Estudiantes";
    private Gestion_Estudiante estudiantesBll = new Gestion_Estudiante();

    private void iniciarListado() throws IOException {

        estudiantesBll.leerEstudiantes();

    }

    /**
     * Creates new form frmRegistroEstudiante
     */
    public frmRegistroEstudiante() {
        initComponents();
        try {
            iniciarListado();

        } catch (IOException ex) {
            Util.imprimir(ex.toString());
        }
    }

    public String verificarClub(JCheckBox chk) {
        if (chk.isSelected()) {
            return chk.getText();
        }
        return "";
    }

    private void CrearEstudiante() {
        Estudiante nuevo = new Estudiante();
        nuevo.setApellido(this.txtApellido1.getText());
        nuevo.setNombre(this.txtNombre1.getText());
        nuevo.setCedula(this.txtCedula1.getText());
        nuevo.setCarrera(this.cmbCarrera.getSelectedItem().toString());

        nuevo.addClub(verificarClub(chkDanza));
        nuevo.addClub(verificarClub(chkMusica));
        nuevo.addClub(verificarClub(chkAndinismo));
        nuevo.addClub(verificarClub(chkAjedres));
        nuevo.addClub(verificarClub(chkFutbol));
        nuevo.addClub(verificarClub(chkArtes));
        nuevo.addClub(verificarClub(chkRobotica));
        nuevo.addClub(verificarClub(chkTenis));

        estudiantesBll.getEstudiantes().add(nuevo);

    }

    private void Archivar() throws IOException {
        estudiantesBll.archivar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblRegistroEstudiante = new javax.swing.JLabel();
        pnlAcademicos = new javax.swing.JPanel();
        lblCedula = new javax.swing.JLabel();
        cmbCarrera = new javax.swing.JComboBox<>();
        pnlDatosPersonales = new javax.swing.JPanel();
        txtCedula1 = new javax.swing.JTextField();
        lblCedula1 = new javax.swing.JLabel();
        lblNombre1 = new javax.swing.JLabel();
        txtNombre1 = new javax.swing.JTextField();
        lblApellido1 = new javax.swing.JLabel();
        txtApellido1 = new javax.swing.JTextField();
        pnlExtracurricular = new javax.swing.JPanel();
        chkDanza = new javax.swing.JCheckBox();
        chkAndinismo = new javax.swing.JCheckBox();
        chkRobotica = new javax.swing.JCheckBox();
        chkMusica = new javax.swing.JCheckBox();
        chkAjedres = new javax.swing.JCheckBox();
        chkFutbol = new javax.swing.JCheckBox();
        chkTenis = new javax.swing.JCheckBox();
        chkArtes = new javax.swing.JCheckBox();
        btnGuarda = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        lblRegistroEstudiante.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblRegistroEstudiante.setText("Registro Estudiante");

        pnlAcademicos.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Datos del Academicos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(14, 22, 14))); // NOI18N

        lblCedula.setText("Carrera:");

        cmbCarrera.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ingenieria de Software", "Ingenieria de Mecatronica", "Ingenieria de Electronica", "Ingenieria de Automotriz" }));

        javax.swing.GroupLayout pnlAcademicosLayout = new javax.swing.GroupLayout(pnlAcademicos);
        pnlAcademicos.setLayout(pnlAcademicosLayout);
        pnlAcademicosLayout.setHorizontalGroup(
            pnlAcademicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAcademicosLayout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(lblCedula)
                .addGap(53, 53, 53)
                .addComponent(cmbCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(86, Short.MAX_VALUE))
        );
        pnlAcademicosLayout.setVerticalGroup(
            pnlAcademicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAcademicosLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(pnlAcademicosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCedula)
                    .addComponent(cmbCarrera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pnlDatosPersonales.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Datos del Personales", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(14, 22, 14))); // NOI18N

        lblCedula1.setText("Cedula:");

        lblNombre1.setText("Nombre:");

        lblApellido1.setText("Apellido:");

        javax.swing.GroupLayout pnlDatosPersonalesLayout = new javax.swing.GroupLayout(pnlDatosPersonales);
        pnlDatosPersonales.setLayout(pnlDatosPersonalesLayout);
        pnlDatosPersonalesLayout.setHorizontalGroup(
            pnlDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosPersonalesLayout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addGroup(pnlDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblApellido1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblCedula1)
                        .addComponent(lblNombre1)))
                .addGap(46, 46, 46)
                .addGroup(pnlDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtApellido1, javax.swing.GroupLayout.DEFAULT_SIZE, 328, Short.MAX_VALUE)
                    .addComponent(txtNombre1)
                    .addComponent(txtCedula1))
                .addContainerGap(107, Short.MAX_VALUE))
        );
        pnlDatosPersonalesLayout.setVerticalGroup(
            pnlDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDatosPersonalesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtCedula1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCedula1))
                .addGap(8, 8, 8)
                .addGroup(pnlDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombre1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtApellido1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblApellido1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlExtracurricular.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Datos del Extracurrriculares", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(14, 22, 14))); // NOI18N

        chkDanza.setText("Club Danza");
        chkDanza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkDanzaActionPerformed(evt);
            }
        });

        chkAndinismo.setText("Club Andinismo ");
        chkAndinismo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkAndinismoActionPerformed(evt);
            }
        });

        chkRobotica.setText("Club Robotica");

        chkMusica.setText("Club Musica");

        chkAjedres.setText("Club Ajedrez");

        chkFutbol.setText("Club Futbol");
        chkFutbol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkFutbolActionPerformed(evt);
            }
        });

        chkTenis.setText("Club Tenis de Mesa");

        chkArtes.setText("Club Artes Plasticas");

        javax.swing.GroupLayout pnlExtracurricularLayout = new javax.swing.GroupLayout(pnlExtracurricular);
        pnlExtracurricular.setLayout(pnlExtracurricularLayout);
        pnlExtracurricularLayout.setHorizontalGroup(
            pnlExtracurricularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlExtracurricularLayout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(pnlExtracurricularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkDanza)
                    .addComponent(chkRobotica)
                    .addComponent(chkAndinismo)
                    .addComponent(chkMusica))
                .addGap(125, 125, 125)
                .addGroup(pnlExtracurricularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkAjedres)
                    .addComponent(chkFutbol)
                    .addComponent(chkTenis)
                    .addComponent(chkArtes))
                .addContainerGap(181, Short.MAX_VALUE))
        );
        pnlExtracurricularLayout.setVerticalGroup(
            pnlExtracurricularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlExtracurricularLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(pnlExtracurricularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkDanza)
                    .addComponent(chkAjedres))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlExtracurricularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkFutbol)
                    .addComponent(chkAndinismo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlExtracurricularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkRobotica)
                    .addComponent(chkTenis))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlExtracurricularLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(chkMusica)
                    .addComponent(chkArtes))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        btnGuarda.setBackground(new java.awt.Color(255, 153, 153));
        btnGuarda.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnGuarda.setForeground(new java.awt.Color(204, 0, 102));
        btnGuarda.setText("Guardar");
        btnGuarda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(264, 264, 264)
                .addComponent(lblRegistroEstudiante)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 43, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnlExtracurricular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlAcademicos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlDatosPersonales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGuarda, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(lblRegistroEstudiante)
                .addGap(18, 18, 18)
                .addComponent(pnlDatosPersonales, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlAcademicos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlExtracurricular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnGuarda, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(117, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chkAndinismoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkAndinismoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkAndinismoActionPerformed

    private void chkFutbolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkFutbolActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkFutbolActionPerformed

    private void chkDanzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkDanzaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkDanzaActionPerformed

    private void btnGuardaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardaActionPerformed
        try {
            CrearEstudiante();
            Archivar();
            vtnPrincipal.verMensaje("Estudiante agregado correctamente", titulo, JOptionPane.INFORMATION_MESSAGE);

        } catch (Exception e) {
            Util.imprimir("Error:" + e.toString());
            vtnPrincipal.verMensaje("Error al guardar el Estudiante", titulo, JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_btnGuardaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuarda;
    private javax.swing.JCheckBox chkAjedres;
    private javax.swing.JCheckBox chkAndinismo;
    private javax.swing.JCheckBox chkArtes;
    private javax.swing.JCheckBox chkDanza;
    private javax.swing.JCheckBox chkFutbol;
    private javax.swing.JCheckBox chkMusica;
    private javax.swing.JCheckBox chkRobotica;
    private javax.swing.JCheckBox chkTenis;
    private javax.swing.JComboBox<String> cmbCarrera;
    private javax.swing.JLabel lblApellido1;
    private javax.swing.JLabel lblCedula;
    private javax.swing.JLabel lblCedula1;
    private javax.swing.JLabel lblNombre1;
    private javax.swing.JLabel lblRegistroEstudiante;
    private javax.swing.JPanel pnlAcademicos;
    private javax.swing.JPanel pnlDatosPersonales;
    private javax.swing.JPanel pnlExtracurricular;
    private javax.swing.JTextField txtApellido1;
    private javax.swing.JTextField txtCedula1;
    private javax.swing.JTextField txtNombre1;
    // End of variables declaration//GEN-END:variables
}
